import "./globals.css";
import { IoIosArrowUp } from "react-icons/io";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <div className="h-[40px] w-[40px] flex items-center justify-center z-20 fixed right-[40px] text-[#01579b] cursor-pointer text-center text-[30px] mb-[-20px] rounded-full border border-[#01579b] transition-colors hover:bg-[#01579b] bottom-10 hover:text-white">
          <a href="#top">
            <IoIosArrowUp />
          </a>
        </div>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
